<a href="https://colab.research.google.com/github/nevestomas2003-web/MachineLearning/blob/main/exercicios_pp_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np

a=np.array([1,2,3,4])
print(a)

b=a.ndim
print(b)
c=a.shape
print(c)
d=len(a)
print(d)

vetor_teste=np.array([3.4,5.8,21.1,2.3])
print(vetor_teste)

[1 2 3 4]
1
(4,)
4
[ 3.4  5.8 21.1  2.3]


In [24]:
#array bidimensional

a=np.array([[1,2,1,4,5],[1,2,1,4,5],[1,2,1,4,5]])
print(a)
b=a.ndim
print(b)
c=a.shape
print(c)

[[1 2 1 4 5]
 [1 2 1 4 5]
 [1 2 1 4 5]]
2
(3, 5)


In [29]:
a=np.arange(10)
print(a)

b=np.arange(2,11,2)
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10]


In [32]:
import numpy as np

a=np.arange(80)

b=a.reshape(8,10)
print(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]


In [40]:
import numpy as np

# 1. Crias as tuas 3 folhas separadamente
folha_uns = np.ones((3, 3))
folha_zeros = np.zeros((3, 3))
folha_diagonal = np.diag([1, 2, 3])

# 2. Juntas tudo no mesmo "ficheiro" (o tal array 3D)
array_final = np.array([folha_uns, folha_zeros, folha_diagonal])

print(array_final)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[1. 0. 0.]
  [0. 2. 0.]
  [0. 0. 3.]]]


In [58]:
import numpy as np

rng=np.random.default_rng()

lista = [1, 2, 3, 4, 5]
rng.shuffle(lista)
print("Lista baralhada:", lista)

y=rng.integers(10, size=5)
print(y)



Lista baralhada: [1, 4, 3, 2, 5]
[8 8 1 8 3]


In [77]:
import numpy as np

a = np.arange(0, 7)

b = np.linspace(0, 6, 7)

c=np.diag((1,1,1,1))
print("escreve o a\n",a, "escreve o b\n", b,
      "\n depois o c\n",c)

rng = np.random.default_rng()

# 2. Criar a folha de Excel 5x5 com números entre [0, 1[
# Nota: passamos um tuple (5, 5) para avisar que queremos 5 linhas e 5 colunas
matriz = rng.random((5, 5))

# 3. Arredondar tudo a 2 casas decimais com a ferramenta np.round()
matriz_arredondada = np.round(matriz, 2)

# 4. Encontrar o valor mínimo e máximo
valor_minimo = matriz_arredondada.min()
valor_maximo = matriz_arredondada.max()

# Mostrar os resultados no ecrã
print("Matriz 5x5:\n", matriz_arredondada)
print("\nMínimo:", valor_minimo)
print("Máximo:", valor_maximo)

escreve o a
 [0 1 2 3 4 5 6] escreve o b
 [0. 1. 2. 3. 4. 5. 6.] 
 depois o c
 [[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
Matriz 5x5:
 [[0.99 0.33 0.52 0.37 0.16]
 [0.43 0.51 0.17 0.65 0.99]
 [0.47 0.83 0.08 0.13 0.3 ]
 [0.26 0.43 0.36 0.23 0.18]
 [0.98 0.05 0.67 0.05 0.64]]

Mínimo: 0.05
Máximo: 0.99


In [86]:
a=np.array([5,3,9,1])


a.sort()

print(a)



[1 3 5 9]


In [95]:
import numpy as np

a=np.arange(36).reshape(6,6)
print(a)

b=a[0, 4:6:1]
print(b)

c=a[2:5:2, 0::2]
print(c)

d=a[4::1 , 4::1]
print(d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[4 5]
[[12 14 16]
 [24 26 28]]
[[28 29]
 [34 35]]


In [104]:
a=np.array([1,2,3,4])
b=np.arange(4)


print(a)
print(b)
print(a+b)
print(a-b)

x=np.array([[1,2,3],[2,3,1]])
y=np.array([[4,5],[3,2],[1,1]])

print("\n",x)
print("\n",y)
print(np.dot(x,y))




[1 2 3 4]
[0 1 2 3]
[1 3 5 7]
[1 1 1 1]

 [[1 2 3]
 [2 3 1]]

 [[4 5]
 [3 2]
 [1 1]]
[[13 12]
 [18 17]]


In [106]:
import numpy as np

quantidades = np.array([2, 3])   # 2 maçãs, 3 bananas
precos = np.array([10, 5])       # 10€ e 5€

fatura = np.dot(quantidades, precos)
print(fatura)


35


In [122]:
import numpy as np
a=np.arange(1,4,1)
b=np.arange(4,7,1)

print(a)
print(b)

c=a*b
print(c)

print(np.dot(a,b))


#Compare the 2 arrays
##Element wise
###array-wise

print(a==b)
np.array_equal(a,b)

[1 2 3]
[4 5 6]
[ 4 10 18]
32
[False False False]


False

In [133]:
a=np.array([[1,2,9],[2,4,8],[1,2,9],[2,4,8]])
print(a)
b=np.sort(a[:,2])
print(b)

print(a.ravel())


[[1 2 9]
 [2 4 8]
 [1 2 9]
 [2 4 8]]
[8 8 9 9]
[1 2 9 2 4 8 1 2 9 2 4 8]


In [153]:
import numpy as np

a=np.array([[2,5,7],[8,3,5],[9,1,1]])
print(a)
b=np.sort(a, axis=0)
print(b)

b=a.T
print(b)

c = np.array([0, 1, 2])

print(b+c)


[[2 5 7]
 [8 3 5]
 [9 1 1]]
[[2 1 1]
 [8 3 5]
 [9 5 7]]
[[2 8 9]
 [5 3 1]
 [7 5 1]]
[[ 2  9 11]
 [ 5  4  3]
 [ 7  6  3]]
