<a href="https://colab.research.google.com/github/nevestomas2003-web/MachineLearning/blob/main/exerciciosfolha2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#exercicio10
#Rever!!!

import numpy as np

a=np.array([5,3,9,1])
print("Original array: ", a)
print("arguments of the sorted elementes ascending ", np.argsort(a))

Original array:  [5 3 9 1]
arguments of the sorted elementes ascending  [3 1 0 2]


In [10]:
import numpy as np

a=np.arrange(36).reshape(6,6)
c=np.copy(a[12:28:2])
b=np.copy(a[3:4:1])

print("escreve a", c)



escreve a []


In [23]:
import numpy as np

a=np.arange(36).reshape(6,6)
c=np.copy(a[2:5:2,0:6:2])
b=np.copy(a[0,3:5:1])
e=np.copy(a[4:7:1,4:6:1])

print(a)
print(b)
print(c)
print(e)


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
[3 4]
[[12 14 16]
 [24 26 28]]
[[28 29]
 [34 35]]


In [33]:
import numpy as np

a=np.array([1,2,3])
b=np.array([4,5,6])

c=a*b
print(c)

print(np.dot(a,b))



[ 4 10 18]
32


In [35]:
import numpy as np
a=np.array([[2,5,7],[8,3,5],[9,1,1]])
print(a)
sorted_rows = np.sort(a, axis=1)
print("Linhas ordenadas:\n", sorted_rows)

[[2 5 7]
 [8 3 5]
 [9 1 1]]
Linhas ordenadas:
 [[2 5 7]
 [3 5 8]
 [1 1 9]]


In [37]:
transpose = a.T
print("Transposta:\n", transpose)

Transposta:
 [[2 8 9]
 [5 3 1]
 [7 5 1]]


In [51]:
import numpy as np

age=np.array([[24,30,45,50,35],[70,80,90,85,75]])


#tabela = np.column_stack([age, weight])
transpose=age.T
print(transpose)



[[24 70]
 [30 80]
 [45 90]
 [50 85]
 [35 75]]
